regress: Fix celerite gradients
Celerite needs `autograd` for its gradient calculation:

ImportError: 'autograd' must be installed to compute gradients

Since we use "l-bfgs-b" for fitting and the celerite provided jacobian,
we also depend on autograd.